# -*- coding: utf-8 -*-
"""Apply remaining EN->HI translations to ai-tools-hi.html"""
from pathlib import Path

PATH = Path(__file__).resolve().parents[1] / "pages" / "ai-tools-hi.html"
text = PATH.read_text(encoding="utf-8")

PAIRS = [
    ("Emails, articles, stories, scripts, social posts", "ईमेल, लेख, कहानियाँ, स्क्रिप्ट, सोशल पोस्ट"),
    ("Explanations on any topic, from math to philosophy", "किसी भी विषय पर व्याख्या, गणित से दर्शन तक"),
    ("Write code, debug, explain existing code", "कोड लिखना, डिबग करना, मौजूदा कोड समझाना"),
    ("Translate between dozens of languages with context", "दर्जनों भाषाओं में संदर्भ के साथ अनुवाद"),
    ("Summarize documents, analyze data, extract insights", "दस्तावेज़ सारांश, डेटा विश्लेषण, अंतर्दृष्टि निकालना"),
    ("Ideas, brainstorming, problem-solving", "विचार, ब्रेनस्टॉrming, समस्या-समाधान"),
    ("Limited access to GPT-5.2", "GPT-5.2 तक सीमित पहुँच"),
    ("Extended access to GPT-5.2, thinking models and advanced tasks", "GPT-5.2, thinking मॉडल और उन्नत कार्यों तक विस्तारित पहुँच"),
    ("Unlimited GPT-5.2 messages, integrations (Slack, Google Drive, GitHub) and security for organizations", "असीमित GPT-5.2 संदेश, एकीकरण (Slack, Google Drive, GitHub) और संगठनों के लिए सुरक्षा"),
    ("Custom pricing, full security and dedicated support", "कस्टम मूल्य, पूर्ण सुरक्षा और समर्पित सहायता"),
    ('Be specific: "Write a professional 3-paragraph email to a supplier who is late, firm but respectful tone"', '"3 अनुच्छेदों का पेशेवर ईमेल लिखें जो देर से आपूर्तिकर्ता को, दृढ़ लेकिन सम्मानजनक स्वर में"'),
    ('Give context: "I\'m a 5th grade teacher, explain X at an appropriate level"', 'संदर्भ दें: "मैं पाँचवीं कक्षा का शिक्षक हूँ, X को उपयुक्त स्तर पर समझाएँ"'),
    ('Ask for options: "Give me 5 possible headlines"', 'विकल्प माँगें: "मुझे 5 संभावित शीर्षक दें"'),
    ('Iterate: "Shorter", "Less formal", "Add an example"', 'सुधारें: "छोटा", "कम औपचारिक", "उदाहरण जोड़ें"'),
    ("Claude is developed by Anthropic, founded by ex-OpenAI staff. It focuses on safety and reliability, and excels at long-document analysis, quality writing, and complex reasoning. As of 2026 the flagship is Claude Opus 4.5 (November 2025) – 200K context, extended thinking, and strong at code, agents, and automation.",
     "Claude Anthropic द्वारा विकसित है, OpenAI के पूर्व कर्मचारियों द्वारा स्थापित। यह सुरक्षा और विश्वसनीयता पर केंद्रित है, और लंबे दस्तावेज़ विश्लेषण, गुणवत्ता लेखन और जटिल तर्क में उत्कृष्ट है। 2026 तक फ़्लैगशिप Claude Opus 4.5 (नवंबर 2025) है – 200K संदर्भ, extended thinking, और कोड, एजेंट और स्वचालन में मजबूत।"),
    ("Up to 200,000 tokens – a whole book or hundreds of pages", "200,000 टोकens तक – पूरी किताब या सैकड़ों पृष्ठ"),
    ("Upload PDFs, code files, and docs for analysis", "विश्लेषण के लिए PDF, कोड फ़ाइलें और दस्तावेज़ अपलोड करें"),
    ('Fewer "hallucinations" – tends to say when it doesn\'t know', 'कम "hallucinations" – जब नहीं जानता तो कहता है'),
    ("Natural, flowing style, great for long-form content", "प्राकृतिक, प्रवाहIT शैली, लंबी सामग्री के लिए उत्कृष्ट"),
    ("Strong programming with detailed explanations", "विस्तृत व्याख्या के साथ मजबूत प्रोग्रामिंग"),
    ("Access to Haiku or Sonnet with usage limits", "उपयोग सीमा के साथ Haiku या Sonnet तक पहुँच"),
    ("Preferred access to Claude Opus 4.5, more messages and quotas", "Claude Opus 4.5 तक प्राथमिकता, अधिक संदेश और कोटा"),
    ("Org plans with higher quotas and Opus 4.5", "उच्च कोटा और Opus 4.5 के साथ संगठन योजनाएँ"),
    ("Gemini is Google's chatbot and platform. Its big advantage is integration with Google products (Gmail, Docs, Drive) and access to up-to-date information from the web. As of 2026 Google offers Google AI Pro and Google AI Ultra (~$250/month) with advanced models, Veo 3 for video, enhanced NotebookLM, and more.",
     "Gemini Google का चैटबॉट और प्लेटफ़ॉर्म है। इसका बड़ा लाभ Google उत्पादों (Gmail, Docs, Drive) के साथ एकीकरण और वेब से अद्यतन जानकारी की पहुँच है। 2026 तक Google Google AI Pro और Google AI Ultra (~$250/माह) उन्नत मॉडल, वीडियो के लिए Veo 3, बेहतर NotebookLM और अधिक के साथ प्रदान करता है।"),
    ("Real-time Google Search results", "रियल-टाइम Google Search परिणाम"),
    ("Works with Gmail, Docs, Drive, Maps", "Gmail, Docs, Drive, Maps के साथ काम करता है"),
    ("Understands images, text, and code", "चित्र, पाठ और कोड समझता है"),
    ("Strong free version", "मजबूत मुफ़्त संस्करण"),
    ("Connect to external services", "बाहरी सेवाओं से कनेक्ट करें"),
    ("Generous Gemini access", "उदार Gemini पहुँच"),
    ("Advanced models, NotebookLM, integrations", "उन्नत मॉडल, NotebookLM, एकीकरण"),
    ("Full Pro Deep Think, Veo 3, 25K AI credits, 30TB storage, YouTube Premium, and more", "पूर्ण Pro Deep Think, Veo 3, 25K AI क्रedit, 30TB स्टोरेज, YouTube Premium, और अधिक"),
    ("A Google tool that builds a personal AI assistant from the documents, PDFs, and sources you upload. Great for research, exam prep, summarizing papers, and asking questions about your material.",
     "Google उपकरण जो आपके अपलोड किए दस्तावेज़, PDF और स्रोतों से व्यक्तिगत एआई सहायक बनाता है। शोध, परीक्षा तैyारी, पेपर सारांश और अपनी सामग्री पर प्रश्न पूछने के लिए उत्कृष्ट।"),
    ('Upload files and build one "notebook"', 'फ़ाइलें अपलोड करें और एक "notebook" बनाएँ'),
    ("Ask questions over all material in the notebook", "notebook की सभी सामग्री पर प्रश्न पूछें"),
    ("Create summaries, study guides, and more", "सारांश, अध्ययन गाइड और अधिक बनाएँ"),
    ('Turn the notebook into a "podcast" to listen to', 'notebook को सुनने के लिए "podcast" में बदलें'),
    ("Gems are custom AI assistants inside Gemini. Google and developers create Gems for specific topics – writing, code, translation, nutrition, interview prep, and more. You can also create your own Gem from a custom prompt.",
     "Gems Gemini के अंदर कस्टम एआई सहायक हैं। Google और डेवलपर विशिष्ट विषयों – लेखन, कोड, अनुवाद, पोषण, इंटरव्यू तैyारी – के लिए Gems बनाते हैं। आप कस्टम प्रॉम्प्ट से अपना Gem भी बना सकते हैं।"),
    ("Writing helper, coder, math tutor, translator, and more", "लेखन सहायक, कोडर, गणित शिक्षक, अनुवादक, और अधिक"),
    ("Set behavior and context and work with one fixed personal assistant", "व्यवहार और संदर्भ सेट करें और एक निश्चित व्यक्तिगत सहायक के साथ काम करें"),
    ("Microsoft's assistant is built into Windows, Office, and Edge, and in paid plans uses advanced models too. Free chat and image creation with web search (Bing).",
     "Microsoft का सहायक Windows, Office और Edge में निर्मित है, और paid योजनाओं में उन्नत मॉडल भी उपयोग करता है। Bing वेब खोज के साथ मुफ़्त चैट और छवि निर्माण।"),
    ("Smart assistant with search and Office integration", "खोज और Office एकीकरण के साथ स्मार्ट सहायक"),
    ("In Word, Excel, PowerPoint", "Word, Excel, PowerPoint में"),
    ("DALL-E 3 built in for free", "मुफ़्त में अंतर्निहित DALL-E 3"),
    ("Connected to Bing for current results", "वर्तमान परिणामों के लिए Bing से जुड़ा"),
    ("🎨 Image generation", "🎨 छवि निर्माण"),
    (" (in ChatGPT Plus) | ", " (ChatGPT Plus में) | "),
    (" (free)", " (मुफ़्त)"),
    ("OpenAI's most advanced image model. DALL-E 3 understands complex prompts, creates images with correct text, and produces great results from simple descriptions.",
     "OpenAI का सबसे उन्नत छवि मॉडल। DALL-E 3 जटिल प्रॉम्प्ट समझता है, सही पाठ वाली छवियाँ बनाता है, और सरल विवरण से बेहतरीन परिणाम देता है।"),
    ("Understands detailed, complex descriptions", "विस्तृत, जटिल विवरण समझता है"),
    ("Text in images: signs and readable titles", "छवियों में पाठ: संकेत और पढ़ने योग्य शीर्षक"),
    ("Integrated with ChatGPT for prompt refinement", "प्रॉम्प्ट सुधार के लिए ChatGPT के साथ एकीकृत"),
    ("Styles: photo, painting, 3D, illustration, and more", "शैliyan: फ़ोटो, पेंटिंग, 3D, चित्रण, और अधिक"),
    ("Via Microsoft Copilot (limited images/day)", "Microsoft Copilot के माध्यम से (सीमित छवियाँ/दिन)"),
    ("DALL-E 3 in chat", "चैट में DALL-E 3"),
    ("Beloved by designers and artists. Midjourney produces high-quality artistic images with a unique aesthetic. Works via Discord.",
     "डिज़ाइनरों और कलाकारों द्वारा पसंदीदा। Midjourney अनूठी सौंदर्यशास्तra के साथ उच्च गुणवत्ता वाली कलात्मक छवियाँ बनाता है। Discord के माध्यम से काम करता है।"),
    ("Basic ($10/mo): ~200 images", "Basic ($10/माह): ~200 छवियाँ"),
    ("Standard ($30/mo): ~900 images + fast mode", "Standard ($30/माह): ~900 छवियाँ + fast mode"),
    ("Pro ($60/mo): Unlimited", "Pro ($60/माह): असीमित"),
    ("Powerful platform with a generous free tier. Great for game assets, fantasy art, and consistent character images.",
     "उदार मुफ़्त tier के साथ शक्तिशाली प्लेटफ़ॉर्म। गेम assets, fantasy art और सुसंगत character छवियों के लिए उत्कृष्ट।"),
    ("Canva now includes built-in AI: image generation, one-click background removal, image expand, and automatic presentation design.",
     "Canva में अब अंतर्निहित एआई: छवि निर्माण, एक-क्लिक पृष्ठभूमि हटाना, छवि विस्तार, और स्वचालित प्रस्तुति डिज़ाइन।"),
    ("Easy to use, ready-made templates, free tier is enough for most uses.", "उपयोग में आसान, तैyार टेmplates, अधिकांश उपयोग के लिए मुफ़्त tier पर्याप्त।"),
    ("Adobe's image tool. Trained only on licensed content, so outputs are safe for commercial use.",
     "Adobe का छवि उपकरण। केवल licensed सामग्री पर प्रशिक्षित, इसलिए आउटपुट व्यावसायिक उपयोग के लिए सुरक्षित।"),
    ("✍️ Writing and editing", "✍️ लेखन और संपादन"),
    ("Leading tool for English writing. Checks grammar, spelling, punctuation, style, and clarity – suggests fixes in real time. With AI it can rewrite and improve tone.",
     "अंग्रेज़ी लेखन के लिए अग्रणी उपकरण। व्याकरण, वर्तनी, विराम चिह्न, शैली और स्पष्टता जाँचता है – रियल-टाइम सुधार सुझाता है। एआई के साथ पुनर्लेखन और स्वर सुधार सकता है।"),
    ("Free: Basic checks", "मुफ़्त: बुनियादी जाँच"),
    ("Premium ($12/mo): Full features + AI", "Premium ($12/माह): पूर्ण सुविधाएँ + एआई"),
    ("Notion has built-in AI to write, summarize, translate, and answer questions from your docs.",
     "Notion में लिखने, सारांश, अनुवाद और आपके दस्तावेज़ों से प्रश्नों के उत्तर के लिए अंतर्निहित एआई है।"),
    ("AI platform for marketing content: ads, landing pages, emails, social posts.",
     "मार्कeting सामग्री के लिए एआई प्लेटफ़ॉर्म: विज्ञापन, landing pages, ईमेल, सोशल पोस्ट।"),
    ("Improves clarity: flags overly complex sentences, passive voice, and excess adjectives.",
     "स्पष्टता सुधारता है: अत्यधिक जटिल वाक्य, passive voice और अतिरिक्त विशेषण चिह्नित करता है।"),
    ("Paraphrasing tool. Rewrite in different styles, avoid plagiarism, vary language.",
     "पैraphrasing उपकरण। अलग शैliyan में पुनर्लेखन, साहित्यिक चोरी से बचें, भाषा विविधता।"),
    ("🎥 Video and audio", "🎥 वीडियो और ऑडियो"),
    ("Leading text-to-speech. Voices sound very human, with emotion and intonation. Clone existing voices or create new ones. Supports 30+ languages including Hebrew.",
     "अग्रणी text-to-speech। आवाज़ें बहुत मानवीय, भावना और intonation के साथ। मौजूदा आवाज़ clone या नई बनाएँ। हिब्रू सहित 30+ भाषाएँ।"),
    ("AI video editing: Gen-2 text-to-video, green screen removal, inpainting, slow motion, and more. Used in Hollywood productions.",
     "एआई वीडियो संपादन: Gen-2 text-to-video, green screen हटाना, inpainting, slow motion, और अधिक। Hollywood production में उपयोग।"),
    ("Edit audio and video by editing the transcript. Delete a word in the text – it's removed from the recording. Great for podcasts and YouTube.",
     "ट्रांसक्रिप्ट संपादित करके ऑडियो और वीडियो संपादित करें। पाठ में शब्द हटाएँ – रिकॉर्डिंग से हट जाता है। podcast और YouTube के लिए उत्कृष्ट।"),
    ("Create music with AI. Describe a song or add lyrics – get a full track with vocals and production. Free tier: 50 creations per day.",
     "एआई से संगीत बनाएँ। गीत का वर्णन या lyrics जोड़ें – vocals और production के साथ पूरा track। मुफ़्त tier: 50/n दिन।"),
    ("Create videos with a talking AI avatar. Pick a character, write script – the avatar speaks naturally. Great for training and marketing.",
     "बोलते एआई avatar के साथ वीडियो बनाएँ। character चुनें, script लिखें – avatar प्राकृतिक रूप से बोलता है। training और marketing के लिए उत्कृष्ट।"),
    ("Smart search that gives summarized answers with sources instead of a list of links. Like asking an expert who read the whole internet. Free tier is generous; Pro adds GPT-5.2, Claude, and more.",
     "स्मार्ट खोज जो लिंक सूची के बजाय स्रोतों के साथ सारांशित उत्तर देती है। जैसे पूरा इंटरनेट पढ़े expert से पूछना। मुफ़्त tier उदार; Pro GPT-5.2, Claude और अधिक जोड़ता है।"),
    ("Auto-transcribes meetings (Zoom/Teams/Meet), live transcript, speaker ID, and automatic summary with action items.",
     "मीटings (Zoom/Teams/Meet) स्वचालित ट्रांसक्राइब, live transcript, speaker ID, और action items के साथ स्वचालित सारांश।"),
    ("Create professional presentations with AI. Enter a topic or upload a doc – Gamma generates a designed deck with content and images.",
     "एआई से पेशेवर प्रस्तुतियाँ बनाएँ। विषय दर्ज करें या doc अपलोड करें – Gamma सामग्री और छवियों के साथ designed deck बनाता है।"),
    ("Automate tasks between apps (Gmail, Slack, Notion, Sheets, and thousands more) and add AI to the workflow.",
     "ऐpps (Gmail, Slack, Notion, Sheets, और हज़ारों) के बीच कार्य automate करें और workflow में एआई जोड़ें।"),
    ("Open-source workflow automation platform. Connects apps, APIs, and AI tools – similar to Zapier, but you can self-host or use n8n Cloud.",
     "ओpen-source workflow automation प्लेटफ़ॉर्म। ऐpps, API और एआई उपकरण जोड़ता है – Zapier जैसा, लेकिन self-host या n8n Cloud उपयोग कर सकते हैं।"),
    ("Full control, run on your own infrastructure", "पूर्ण नियंत्रण, अपने infrastructure पर चलाएँ"),
    ("Hundreds of integrations:", "सैकड़ों एकीकरण:"),
    ("Connect ChatGPT, Claude, and other models", "ChatGPT, Claude और अन्य मॉडल कनेक्ट करें"),
    ("Build workflows without code, with optional custom JavaScript", "कोड के बिना workflows बनाएँ, वैकल्पिक custom JavaScript"),
    ("No license cost when you run it yourself", "खud चलाने पर कोई license लागत नहीं"),
    ("Paid plans for managed hosting", "managed hosting के लिए paid योजनाएँ"),
    ("Email client with AI: fast replies, thread summaries, smart reminders.", "एआई वाला ईमेल client: तेज़ जवाब, thread सारांश, smart reminders।"),
    ("Notes app with AI that organizes your knowledge. Ask questions about your notes and get answers from what you wrote.", "एआई वाला notes ऐpp जो ज्ञान व्यवस्थित करता है। notes पर प्रश्न पूछें और लिखे से उत्तर पाएँ।"),
    ("Smart calendar. AI schedules meetings, focus time, breaks, and tasks – and adjusts when things change.", "स्मार्ट calendar। एआई meetings, focus time, breaks और tasks शेड्यूल करता है – और बदलाव पर adjust करता है।"),
    ("📌 Tips for better use", "📌 बेहतर उपयोग के सुझाव"),
    ("1. Be specific", "1. विशिष्ट रहें"),
    ('Instead of "help me write" → "Write a short 3-paragraph email to a supplier who is late with delivery, professional but firm tone."',
     '"मुझे लिखने में मदद करो" के बजाय → "3 अनुच्छेदों का छोटा ईमेल लिखें देर से delivery वाले supplier को, पेशेवर लेकिन दृढ़ स्वर में।"'),
    ("2. Give context", "2. संदर्भ दें"),
    ("Tell the AI who you are, who the text is for, and what the goal is.", "एआई को बताएँ आप कौन हैं, पाठ किसके लिए है, और लक्ष्य क्या है।"),
    ("3. Ask for examples", "3. उदाहरण माँगें"),
    ("If unsure, ask for several options and pick the best.", "अनिश्चित हों तो कई विकल्प माँगें और सर्वोत्तम चुनें।"),
    ("4. Refine", "4. सुधारें"),
    ('If the answer isn\'t perfect, say "shorter", "less formal", "add an example".', 'उत्तर perfect न हो तो "छोटा", "कम औपचारिक", "उदाहरण जोड़ें" कहें।'),
    ("AI can make mistakes – always verify important information", "एआई गलती कर सकती है – महत्वपूर्ण जानकारी हमेशा सत्यापित करें"),
    ("Don't share sensitive or personal data", "संवेदनशील या व्यक्तिगत डेटा साझा न करें"),
    ("Copyright on AI-generated content is still legally unclear", "एआई-जनित सामग्री पर कॉpyright अभी भी कानूनी रूप से अस्पष्ट है"),
    ("Summary – where to start? 📝", "सारांश – कहाँ से शुरू करें? 📝"),
    ("Chat and general help:", "चैट और सामान्य मदद:"),
    ("Images:", "छवियाँ:"),
    ("Canva (beginners) or Midjourney (advanced)", "Canva (शुरुआती) या Midjourney (उन्नत)"),
    ("Research and search:", "शोध और खोज:"),
    ("English writing:", "अंग्रेज़ी लेखन:"),
    ("Meeting notes:", "मीटing notes:"),
    ("Answer 10 questions to check your understanding of AI tools.", "एआई उपकरणों की समझ जाँचने के लिए 10 प्रश्नों के उत्तर दें।"),
    ("What does ChatGPT do?", "ChatGPT क्या करता है?"),
    ("Creates images from text", "पाठ से छवियाँ बनाता है"),
    ("Chatbot for conversation, writing, and problem-solving", "बातचीत, लेखन और समस्या-समाधान के लिए चैटबॉट"),
    ("Edits videos", "वीडियो संपादित करता है"),
    ("Plays music", "संगीत बजाता है"),
    ("Which tool specializes in creating images from text?", "कौन सा उपकरण पाठ से छवि बनाने में विशेषज्ञ है?"),
    ("What does Claude (Anthropic) do?", "Claude (Anthropic) क्या करता है?"),
    ("AI assistant for analysis, writing, and coding", "विश्लेषण, लेखन और कोडिंग के लिए एआई सहायक"),
    ("Creates music", "संगीत बनाता है"),
    ("Edits video", "वीडियो संपादित करता है"),
    ("Video game", "वीडियो गेम"),
    ("What is GitHub Copilot?", "GitHub Copilot क्या है?"),
    ("App for piloting planes", "हवाई जहाज चलाने का ऐpp"),
    ("Social network for developers", "डेवलपरों का सोशल नेटवर्क"),
    ("Image editing software", "छवि संपादन सॉफ़्टवेयर"),
    ("AI that helps write and autocompletes code", "कोड लिखने और ऑटो-कम्पलीट में मदद करने वाला एआई"),
    ("What is important to remember when using AI?", "एआई उपयोग में क्या याद रखना महत्वपूर्ण है?"),
    ("AI is always correct", "एआई हमेशा सही है"),
    ("Check and verify – AI can make mistakes", "जाँचें और सत्यापित करें – एआई गलती कर सकती है"),
    ("We don't need to think for ourselves anymore", "हमें अब खud सोचने की ज़रूरत नहीं"),
    ("You can share any personal information", "कोई भी व्यक्तिगत जानकारी साझा कर सकते हैं"),
    ("What is Google Gemini?", "Google Gemini क्या है?"),
    ("Google video game", "Google वीडियो गेम"),
    ("Web browser", "वेब ब्राउज़र"),
    ("Google's AI for search and content", "खोज और सामग्री के लिए Google का एआई"),
    ("Maps app", "Maps ऐpp"),
    ("What does Grammarly do?", "Grammarly क्या करता है?"),
    ("Checks and improves English writing", "अंग्रेज़ी लेखन जाँचता और सुधारता है"),
    ("Teaches guitar", "गिटar सिखाता है"),
    ("Creates graphics", "ग्राफ़िक्स बनाता है"),
    ("What is a good prompt?", "अच्छा प्रॉम्प्ट क्या है?"),
    ("As short as possible", "जitna छोटा हो सके"),
    ("In English only", "केवल अंग्रेज़ी में"),
    ("With no details", "बिना विवरण के"),
    ("Clear, specific, and with context", "स्पष्ट, विशिष्ट, और संदर्भ के साथ"),
    ("Is it okay to use content generated by AI?", "एआई-जनित सामग्री उपयोग करना ठीक है?"),
    ("Never", "कभी नहीं"),
    ("Yes, but check policies and cite when needed", "हाँ, लेकिन नीतियाँ जाँचें और ज़रूरत पर उद्धृत करें"),
    ("Only if you pay", "केवल भुगतान पर"),
    ("Only for personal use", "केवल व्यक्तिगत उपयोग के लिए"),
    ("What should you not share with AI tools?", "एआई उपकरणों के साथ क्या साझा नहीं करना चाहिए?"),
    ("General questions", "सामान्य प्रश्न"),
    ("Creative requests", "रचनात्मक अनुरोध"),
    ("Sensitive personal data like passwords and ID numbers", "पासवर्ड और ID नंबर जैसा संवेदनशील व्यक्तिगत डेटा"),
    ("Science questions", "विज्ञान प्रश्न"),
    ("Huge context:", "विशाल संदर्भ:"),
    ("Document analysis:", "दस्तावेज़ विश्लेषण:"),
    ("Accuracy:", "सटीकता:"),
    ("Code:", "कोड:"),
    ("Live info:", "live जानकारी:"),
    ("Google integration:", "Google एकीकरण:"),
    ("Multimodal:", "multimodal:"),
    ("Free tier:", "मुफ़्त tier:"),
    ("Add-ons:", "add-ons:"),
    ("Your sources:", "आपके स्रोत:"),
    ("Summaries and content:", "सारांश और सामग्री:"),
    ("Audio:", "ऑडियो:"),
    ("Ready-made Gems:", "तैyार Gems:"),
    ("Custom Gem:", "कस्टom Gem:"),
    ("Office:", "Office:"),
    ("Image creation:", "छवि निर्माण:"),
    ("Search:", "खोज:"),
    ("Open source:", "ओpen source:"),
    ("AI nodes:", "एआई nodes:"),
    ("Visual editor:", "visual editor:"),
    ("Free (self-hosted):", "मुफ़्त (self-hosted):"),
    ("n8n Cloud:", "n8n Cloud:"),
    (" (Gems inside Gemini)", " (Gemini के अंदर Gems)"),
]

for en, hi in sorted(PAIRS, key=lambda x: -len(x[0])):
    text = text.replace(en, hi)

PATH.write_text(text, encoding="utf-8")
print("Updated", PATH.name, "length", len(text))
